version: "3.0"

expectations:
  population_size: 1000

actions:
  # These actions are copied-and-pasted into README.md for user-facing documentation.
  # If you change them here, then please change them there.
  generate_cohort:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition
        --index-date-range "2021-01-01 to 2021-06-30 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_2021-*.csv

  generate_ethnicity_cohort:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_ethnicity
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv

  join_cohorts:
    # For user-facing documentation, call:
    # cohort-joiner:[version]
    run: >
      python:latest analysis/cohort_joiner.py
        --lhs output/input_2021-*.csv
        --rhs output/input_ethnicity.csv
        --overwrite
    needs: [generate_cohort, generate_ethnicity_cohort]
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv
